#!/usr/bin/env bash
set -euo pipefail

AGENTS_DIR=".agents/skills"
HEADER="<!-- Generated by scripts/sync-skills.sh — do not edit directly. Edit files in .agents/skills/ instead. -->"

if [[ ! -d "$AGENTS_DIR" ]]; then
  echo "Error: '$AGENTS_DIR' directory not found"
  exit 1
fi

shopt -s nullglob
skills=("$AGENTS_DIR"/*)
if [[ ${#skills[@]} -eq 0 ]]; then
  echo "Error: no skill folders found in '$AGENTS_DIR'"
  exit 1
fi

echo "Found ${#skills[@]} skill(s): ${skills[*]}"

for skill_dir in "${skills[@]}"; do
  [[ -d "$skill_dir" ]] || continue
  skill_name=$(basename "$skill_dir")
  src="$skill_dir/SKILL.md"

  if [[ ! -f "$src" ]]; then
    echo "warning: skipping '$skill_name' — no SKILL.md found"
    continue
  fi

  # Extract frontmatter from source if present
  if head -1 "$src" | grep -q '^---$'; then
    # Find the closing --- line
    closing_line=$(tail -n +2 "$src" | grep -n '^---$' | head -1 | cut -d: -f1)
    if [[ -n "$closing_line" ]]; then
      closing_line=$((closing_line + 1))
      frontmatter=$(head -n "$closing_line" "$src")
      body=$(tail -n +$((closing_line + 1)) "$src")
    else
      frontmatter=""
      body=$(cat "$src")
    fi
  else
    frontmatter=""
    body=$(cat "$src")
  fi

  # Claude Code
  dest=".claude/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  {
    [[ -n "$frontmatter" ]] && echo "$frontmatter" && echo
    echo "$HEADER"
    echo
    echo "$body"
  } >"$dest"
  echo "wrote $dest"

  # Qwen
  dest=".qwen/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  {
    [[ -n "$frontmatter" ]] && echo "$frontmatter" && echo
    echo "$HEADER"
    echo
    echo "$body"
  } >"$dest"
  echo "wrote $dest"

  # Gemini — use .agents/skills/ directly (Gemini CLI supports it as alias)

  # Kiro
  dest=".kiro/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  {
    if [[ -n "$frontmatter" ]]; then
      echo "$frontmatter"
    else
      printf -- "---\ninclusion: always\n---"
    fi
    echo
    echo "$HEADER"
    echo
    echo "$body"
  } >"$dest"
  echo "wrote $dest"
done

echo "Skills synced."
