#!/bin/bash
set -e

AGENTS_DIR=".agents/agents"
CLAUDE_DIR=".claude/agents"
KIRO_DIR=".kiro/agents"
QWEN_DIR=".qwen/agents"
HEADER="<!-- Generated by scripts/sync-agents.sh — do not edit directly. Edit files in .agents/agents/ instead. -->"

# Create target directories
mkdir -p "$CLAUDE_DIR" "$KIRO_DIR" "$QWEN_DIR"

# Process each agent file
for agent_file in "$AGENTS_DIR"/*.md; do
    if [ ! -f "$agent_file" ]; then
        continue
    fi
    
    filename=$(basename "$agent_file")
    
    # Extract name and description
    name=$(awk '/^name:/ {sub(/^name: /, ""); print; exit}' "$agent_file")
    description=$(awk '/^description:/ {sub(/^description: /, ""); print; exit}' "$agent_file")
    
    # Extract capabilities
    capabilities=$(awk '/^capabilities:/,/^---$/ {
        if ($0 ~ /^  - /) {
            sub(/^  - /, "")
            print
        }
    }' "$agent_file")
    
    # Get content after second ---
    content=$(awk 'BEGIN {count=0} /^---$/ {count++; next} count>=2 {print}' "$agent_file")
    
    # Map to Claude format
    claude_tools=""
    while IFS= read -r cap; do
        case "$cap" in
            "execute_commands"|"run_shell_command") claude_tools="${claude_tools:+$claude_tools, }Bash" ;;
            "write_files") claude_tools="${claude_tools:+$claude_tools, }Write" ;;
            "read_files") claude_tools="${claude_tools:+$claude_tools, }Read" ;;
            "code_intelligence") claude_tools="${claude_tools:+$claude_tools, }Grep, Glob" ;;
            "delegate_subagents") claude_tools="${claude_tools:+$claude_tools, }Delegate" ;;
        esac
    done <<< "$capabilities"
    
    cat > "$CLAUDE_DIR/$filename" <<EOF
$HEADER

---
name: $name
description: $description
tools: $claude_tools
---

$content
EOF
    
    # Map to Kiro format
    kiro_tools="["
    first=true
    while IFS= read -r cap; do
        if [ "$first" = false ]; then
            kiro_tools="${kiro_tools}, "
        fi
        first=false
        case "$cap" in
            "execute_commands"|"run_shell_command") kiro_tools="${kiro_tools}execute_bash" ;;
            "write_files") kiro_tools="${kiro_tools}fs_write" ;;
            "read_files") kiro_tools="${kiro_tools}fs_read" ;;
            "code_intelligence") kiro_tools="${kiro_tools}code" ;;
            "delegate_subagents") kiro_tools="${kiro_tools}use_subagent" ;;
        esac
    done <<< "$capabilities"
    kiro_tools="${kiro_tools}]"
    
    cat > "$KIRO_DIR/$filename" <<EOF
$HEADER

---
name: $name
description: $description
tools: $kiro_tools
---

$content
EOF
    
    # Map to OpenCode format
    opencode_perms=""
    while IFS= read -r cap; do
        case "$cap" in
            "execute_commands"|"run_shell_command") opencode_perms="${opencode_perms}  shell: true\n" ;;
            "write_files") opencode_perms="${opencode_perms}  write: true\n" ;;
            "read_files") opencode_perms="${opencode_perms}  read: true\n" ;;
            "code_intelligence") opencode_perms="${opencode_perms}  grep: true\n  glob: true\n" ;;
            "delegate_subagents") opencode_perms="${opencode_perms}  delegate: true\n" ;;
        esac
    done <<< "$capabilities"
    
    cat > "$QWEN_DIR/$filename" <<EOF
$HEADER

---
name: $name
description: $description
permissions:
$(echo -e "$opencode_perms")
---

$content
EOF
    
    echo "Synced: $filename"
done

echo "✓ Agent sync complete"
