#!/usr/bin/env bash
set -euo pipefail

AGENTS_DIR=".agents/skills"
HEADER="<!-- Generated by scripts/sync-skills.sh — do not edit directly. Edit files in .agents/skills/ instead. -->"

if [[ ! -d "$AGENTS_DIR" ]]; then
  echo "Error: '$AGENTS_DIR' directory not found"
  exit 1
fi

shopt -s nullglob
skills=("$AGENTS_DIR"/*)
if [[ ${#skills[@]} -eq 0 ]]; then
  echo "Error: no skill folders found in '$AGENTS_DIR'"
  exit 1
fi

echo "Found ${#skills[@]} skill(s): ${skills[*]}"

for skill_dir in "${skills[@]}"; do
  [[ -d "$skill_dir" ]] || continue
  skill_name=$(basename "$skill_dir")
  src="$skill_dir/SKILL.md"

  if [[ ! -f "$src" ]]; then
    echo "warning: skipping '$skill_name' — no SKILL.md found"
    continue
  fi

  # Claude Code
  dest=".claude/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  echo -e "$HEADER\n\n$(cat "$src")" >"$dest"
  echo "wrote $dest"

  # Qwen
  dest=".qwen/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  echo -e "$HEADER\n\n$(cat "$src")" >"$dest"
  echo "wrote $dest"

  # Kiro (needs frontmatter)
  dest=".kiro/skills/$skill_name/SKILL.md"
  mkdir -p "$(dirname "$dest")"
  printf -- "---\ninclusion: always\n---\n\n%s\n\n%s" "$HEADER" "$(cat "$src")" >"$dest"
  echo "wrote $dest"
done

echo "Skills synced."
